# ============================================================
# analytics/rfm_analysis.py
# PURPOSE: Analyse RFM customer segments from mart_rfm
# OUTPUT:  Prints segment summary and saves charts to reports/
# RUN FROM: project root (e_com_analyser)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import os
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from analytics.db import get_engine

# ── SETUP ──────────────────────────────────────────────────────
# Create reports folder if it does not exist
# This is where all charts and CSV outputs will be saved
os.makedirs("reports", exist_ok=True)

print("="*60)
print("  RFM CUSTOMER SEGMENTATION ANALYSIS")
print("="*60)

# ── LOAD DATA ──────────────────────────────────────────────────
# Read the full mart_rfm table into a pandas DataFrame
# A DataFrame is like an Excel table in Python — rows and columns
print("\nLoading mart_rfm from Supabase...")
engine = get_engine()

df = pd.read_sql(
    "SELECT * FROM public_marts.mart_rfm",
    engine
)

print(f"Loaded {len(df):,} customers")

# ── SEGMENT SUMMARY ────────────────────────────────────────────
# Group customers by segment and calculate key metrics per segment
print("\n--- SEGMENT SUMMARY ---")

segment_summary = (
    df.groupby("customer_segment")
    .agg(
        # How many customers are in each segment
        customer_count  = ("customer_unique_id", "count"),

        # Average monetary value per customer in this segment
        avg_spend       = ("monetary_value", "mean"),

        # Total revenue generated by this segment
        total_revenue   = ("monetary_value", "sum"),

        # Average number of orders per customer in this segment
        avg_orders      = ("frequency", "mean"),

        # Average recency in days — how recently they bought
        avg_recency_days = ("recency_days", "mean"),
    )
    .round(2)
    # Sort by total revenue descending — most valuable segments first
    .sort_values("total_revenue", ascending=False)
    .reset_index()
)

# Calculate what percentage of total customers each segment holds
total_customers = len(df)
segment_summary["pct_customers"] = (
    segment_summary["customer_count"] / total_customers * 100
).round(1)

# Calculate what percentage of total revenue each segment generates
total_revenue = df["monetary_value"].sum()
segment_summary["pct_revenue"] = (
    segment_summary["total_revenue"] / total_revenue * 100
).round(1)

print(segment_summary[[
    "customer_segment", "customer_count", "pct_customers",
    "total_revenue", "pct_revenue", "avg_spend", "avg_orders"
]].to_string(index=False))

# ── KEY BUSINESS INSIGHTS ──────────────────────────────────────
print("\n--- KEY INSIGHTS ---")

# Champions: your best customers
champions = segment_summary[
    segment_summary["customer_segment"] == "Champions"
]
if not champions.empty:
    print(f"\nChampions:")
    print(f"  {champions['customer_count'].values[0]:,} customers "
          f"({champions['pct_customers'].values[0]}% of base)")
    print(f"  Generate {champions['pct_revenue'].values[0]}% of total revenue")
    print(f"  Average spend: R${champions['avg_spend'].values[0]:,.2f}")

# At Risk: high value customers going quiet
at_risk = segment_summary[
    segment_summary["customer_segment"] == "At Risk"
]
if not at_risk.empty:
    print(f"\nAt Risk customers:")
    print(f"  {at_risk['customer_count'].values[0]:,} customers going quiet")
    print(f"  Revenue at risk: R${at_risk['total_revenue'].values[0]:,.2f}")
    print(f"  Average days since last purchase: "
          f"{df[df['customer_segment']=='At Risk']['recency_days'].mean():.0f} days")

# Lost customers
lost = segment_summary[
    segment_summary["customer_segment"] == "Lost"
]
if not lost.empty:
    print(f"\nLost customers:")
    print(f"  {lost['customer_count'].values[0]:,} customers "
          f"({lost['pct_customers'].values[0]}% of base) considered lost")

# ── CHART 1: CUSTOMERS PER SEGMENT ────────────────────────────
print("\nGenerating charts...")

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle("RFM Customer Segmentation Analysis", fontsize=16, fontweight="bold")

# Sort by customer count for the bar chart
plot_data = segment_summary.sort_values("customer_count", ascending=True)

colors = [
    "#1D9E75" if seg == "Champions"
    else "#E8593C" if seg in ["At Risk", "Cannot Lose Them", "Lost"]
    else "#5DCAA5" if seg in ["Loyal Customers", "Potential Loyalists"]
    else "#B4B2A9"
    for seg in plot_data["customer_segment"]
]

# Bar chart: number of customers per segment
axes[0].barh(
    plot_data["customer_segment"],
    plot_data["customer_count"],
    color=colors
)
axes[0].set_title("Customers per Segment", fontsize=13)
axes[0].set_xlabel("Number of Customers")
axes[0].xaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x, _: f"{x:,.0f}")
)
axes[0].grid(axis="x", alpha=0.3)

# ── CHART 2: REVENUE PER SEGMENT ──────────────────────────────
plot_data2 = segment_summary.sort_values("total_revenue", ascending=True)

colors2 = [
    "#1D9E75" if seg == "Champions"
    else "#E8593C" if seg in ["At Risk", "Cannot Lose Them", "Lost"]
    else "#5DCAA5" if seg in ["Loyal Customers", "Potential Loyalists"]
    else "#B4B2A9"
    for seg in plot_data2["customer_segment"]
]

axes[1].barh(
    plot_data2["customer_segment"],
    plot_data2["total_revenue"],
    color=colors2
)
axes[1].set_title("Total Revenue per Segment (R$)", fontsize=13)
axes[1].set_xlabel("Total Revenue (R$)")
axes[1].xaxis.set_major_formatter(
    mticker.FuncFormatter(lambda x, _: f"R${x:,.0f}")
)
axes[1].grid(axis="x", alpha=0.3)

plt.tight_layout()
chart_path = "reports/rfm_segments.png"
plt.savefig(chart_path, dpi=150, bbox_inches="tight")
print(f"Chart saved to {chart_path}")

# ── CHART 3: RFM SCORE DISTRIBUTION ───────────────────────────
fig2, ax = plt.subplots(figsize=(10, 5))
fig2.suptitle("RFM Combined Score Distribution", fontsize=14, fontweight="bold")

df["rfm_score"].value_counts().sort_index().plot(
    kind="bar", ax=ax, color="#5DCAA5", edgecolor="white"
)
ax.set_xlabel("RFM Combined Score (3=worst, 15=best)")
ax.set_ylabel("Number of Customers")
ax.set_title("How customers are distributed across RFM scores")
ax.grid(axis="y", alpha=0.3)
plt.xticks(rotation=0)
plt.tight_layout()
chart_path2 = "reports/rfm_score_distribution.png"
plt.savefig(chart_path2, dpi=150, bbox_inches="tight")
print(f"Chart saved to {chart_path2}")

# ── SAVE SUMMARY TO CSV ────────────────────────────────────────
csv_path = "reports/rfm_segment_summary.csv"
segment_summary.to_csv(csv_path, index=False)
print(f"Summary saved to {csv_path}")

print("\n" + "="*60)
print("  RFM ANALYSIS COMPLETE")
print("="*60 + "\n")