-- ============================================================
-- MART: mart_products.sql
-- PURPOSE: Product category performance analysis
-- GRAIN: One row per product category
-- SOURCE: stg_order_items, stg_products, stg_reviews,
--         stg_orders, raw_category_translation
-- ============================================================

with order_items as (

    select * from {{ ref('stg_order_items') }}

),

products as (

    select * from {{ ref('stg_products') }}

),

reviews as (

    select * from {{ ref('stg_reviews') }}

),

orders as (

    -- We need order status and purchased_at from orders
    select
        order_id,
        order_status,
        purchased_at
    from {{ ref('stg_orders') }}

),

-- Pull the English category name translation table
-- This maps Portuguese category names to English
-- e.g. 'beleza_saude' -> 'health_beauty'
category_translation as (

    select
        product_category_name          as category_portuguese,
        product_category_name_english  as category_english
    from {{ source('olist', 'raw_category_translation') }}

),

-- ── JOIN ITEMS TO PRODUCTS AND ORDERS ─────────────────────────
-- We need: item price, product category, order status
-- One row per order item
items_with_category as (

    select
        i.order_id,
        i.product_id,
        i.price,
        i.freight_cost,

        -- Get English category name via translation table.
        -- COALESCE falls back to Portuguese name if no translation exists.
        coalesce(
            t.category_english,
            p.product_category_name,
            'uncategorised'
        ) as category_name,

        o.order_status,
        o.purchased_at

    from order_items i

    left join products p
        on i.product_id = p.product_id

    left join category_translation t
        on p.product_category_name = t.category_portuguese

    left join orders o
        on i.order_id = o.order_id

),

-- ── JOIN REVIEWS TO ITEMS ──────────────────────────────────────
-- Reviews are at order level, not item level.
-- We join them to items via order_id.
-- If an order has 3 items, all 3 items get the same review score.
items_with_reviews as (

    select
        i.category_name,
        i.price,
        i.freight_cost,
        i.order_id,
        i.order_status,
        r.review_score

    from items_with_category i

    left join reviews r
        on i.order_id = r.order_id

),

-- ── AGGREGATE TO CATEGORY GRAIN ───────────────────────────────
final as (

    select
        -- ── CATEGORY NAME ──────────────────────────────────────
        category_name,

        -- ── VOLUME METRICS ─────────────────────────────────────
        -- Total number of items sold in this category
        count(*)                                          as total_items_sold,

        -- Number of unique orders containing this category
        count(distinct order_id)                          as total_orders,

        -- ── REVENUE METRICS ────────────────────────────────────
        -- Total revenue generated by this category
        round(sum(price)::numeric, 2)                     as total_revenue,

        -- Average price per item in this category
        round(avg(price)::numeric, 2)                     as avg_item_price,

        -- Average freight cost for items in this category
        -- Heavy or bulky categories cost more to ship
        round(avg(freight_cost)::numeric, 2)              as avg_freight_cost,

        -- ── REVIEW METRICS ─────────────────────────────────────
        -- Average star rating for this category (1-5)
        -- This is the most important quality signal per category
        round(avg(review_score)::numeric, 2)              as avg_review_score,

        -- How many reviews exist for this category
        count(review_score)                               as total_reviews,

        -- Percentage of reviews that are 5 stars
        -- High 5-star rate = customers love this category
        round(
            sum(case when review_score = 5 then 1 else 0 end)::numeric
            / nullif(count(review_score), 0) * 100,
            1
        )                                                 as pct_five_star,

        -- Percentage of reviews that are 1 star
        -- High 1-star rate = serious quality or fulfilment problem
        round(
            sum(case when review_score = 1 then 1 else 0 end)::numeric
            / nullif(count(review_score), 0) * 100,
            1
        )                                                 as pct_one_star

    from items_with_reviews

    -- Only include delivered orders for fair comparison
    -- A cancelled order's review score is not about the product
    where order_status = 'delivered'
      and category_name is not null

    group by category_name

)

select * from final
order by total_revenue desc